apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: aws-organization
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-organizations
    version: ">=v2"
  - apiVersion: pkg.crossplane.io/v1
    kind: Configuration
    package: ghcr.io/hops-ops/aws-account
    version: '>=v0.16.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: XRD for managing AWS Organizations and organizational units.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # aws-organization

    Creates and configures AWS Organizations with default OU structures based on AWS best practices.
  repository: ghcr.io/hops-ops/aws-organization
  source: github.com/hops-ops/aws-organization
