apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: organizations.aws.hops.ops.com.ai
spec:
  scope: Namespaced
  group: aws.hops.ops.com.ai
  names:
    kind: Organization
    plural: organizations
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              externalName:
                type: string
                description: |
                  Sets the crossplane.io/external-name annotation on the Organization resource.
                  Use this to adopt an existing AWS Organization by specifying its ID (e.g., o-abc123xyz).
                  When set, Crossplane will import the existing organization instead of creating a new one.
              aws:
                properties:
                  providerConfig:
                    type: string
                    description: AWS provider config name to use for organization resources.
                type: object
              managementPolicies:
                description: ManagementPolicies for AWS resources. Defaults to ["*"] which includes all operations (Create, Observe, Update, Delete, LateInitialize). To orphan resources on deletion, use ["Create", "Observe", "Update", "LateInitialize"].
                type: array
                items:
                  type: string
                  enum:
                    - "*"
                    - Create
                    - Observe
                    - Update
                    - Delete
                    - LateInitialize
                default: ["*"]
              organization:
                type: object
                description: |
                  AWS Organization resource settings. Passed directly to the Organization forProvider.
                  Defaults: featureSet=ALL, enabledPolicyTypes=[SERVICE_CONTROL_POLICY, TAG_POLICY, BACKUP_POLICY, AISERVICES_OPT_OUT_POLICY], awsServiceAccessPrincipals=[]
                properties:
                  managementPolicies:
                    description: ManagementPolicies for the Organization resource only. If not set, uses spec.managementPolicies. Use this to orphan the Organization on deletion while still deleting OUs and other child resources.
                    type: array
                    items:
                      type: string
                      enum:
                        - "*"
                        - Create
                        - Observe
                        - Update
                        - Delete
                        - LateInitialize
                x-kubernetes-preserve-unknown-fields: true
              organizationalUnits:
                type: array
                description: |
                  Organizational units to create using path-based hierarchy.
                  Paths define the OU tree structure (e.g., /Security, /Workloads/Prod).
                  Parent OUs are created automatically based on path hierarchy.
                items:
                  type: object
                  properties:
                    path:
                      type: string
                      description: |
                        OU path defining hierarchy (e.g., Security, Workloads/Prod).
                        Parent path must exist in the list for nested OUs.
                      pattern: ^[a-zA-Z0-9-]+(/[a-zA-Z0-9-]+)*$
                    externalName:
                      type: string
                      description: |
                        AWS Organizational Unit ID to adopt (e.g., ou-abc123-xyz789).
                        When set, Crossplane imports the existing OU instead of creating a new one.
                    managementPolicies:
                      type: array
                      description: |
                        ManagementPolicies for this OU. Overrides spec.managementPolicies if set.
                        Use to orphan specific OUs on deletion while deleting others.
                      items:
                        type: string
                        enum:
                          - "*"
                          - Create
                          - Observe
                          - Update
                          - Delete
                          - LateInitialize
                    accounts:
                      type: array
                      description: |
                        Accounts to create under this organizational unit. Fields are passed to Account composite spec.
                        Defaults applied: parentId (from parent OU), managementPolicies (from org), tags (merged with org).
                        Use 'overrideSpec' to skip all defaults and provide complete Account spec.
                      items:
                        type: object
                        required:
                          - name
                          - email
                        properties:
                          name:
                            type: string
                            description: Account name and metadata.name for the Account composite.
                          email:
                            type: string
                            description: AWS account email address. Must be unique across all AWS accounts.
                          externalName:
                            type: string
                            description: |
                              AWS Account ID to adopt (e.g., 123456789012).
                              When set, Crossplane imports the existing account instead of creating a new one.
                          managementPolicies:
                            type: array
                            description: |
                              ManagementPolicies for this account. Overrides spec.managementPolicies if set.
                              Use to orphan specific accounts on deletion while deleting others.
                            items:
                              type: string
                              enum:
                                - "*"
                                - Create
                                - Observe
                                - Update
                                - Delete
                                - LateInitialize
                          overrideSpec:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            description: |
                              Complete Account spec override. When set, skips ALL defaults (parentId, managementPolicies, tag merging).
                              Use for advanced scenarios like importing existing accounts or custom management policies.
                        x-kubernetes-preserve-unknown-fields: true
                  required:
                    - path
              delegatedAdministrators:
                type: array
                description: Delegated administrator accounts for AWS services.
                items:
                  type: object
                  properties:
                    servicePrincipal:
                      type: string
                      description: AWS service principal (e.g., ipam.amazonaws.com, sso.amazonaws.com).
                    accountRef:
                      type: object
                      description: Reference to the Account resource.
                      properties:
                        name:
                          type: string
                      required:
                        - name
                  required:
                    - servicePrincipal
                    - accountRef
              tags:
                type: object
                description: Tags to apply to the organization and OUs.
                x-kubernetes-preserve-unknown-fields: true
            required:
              - managementPolicies
            type: object
          status:
            properties:
              organizationId:
                type: string
                description: AWS Organization ID (e.g., o-abc123xyz).
              managementAccountId:
                type: string
                description: AWS account ID of the management account.
              rootId:
                type: string
                description: Root organizational unit ID.
              organizationalUnits:
                type: object
                description: Map of OU paths to OU IDs.
                x-kubernetes-preserve-unknown-fields: true
              ready:
                type: boolean
                description: Indicates whether the organization and all OUs are ready.
            type: object
        required:
        - spec
        type: object
    served: true
