apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Organization
metadata:
  name: acme
  namespace: acme
spec:
  managementPolicies:
    - "*"
  featureSet: ALL
  organizationalUnits:
    - name: Security
    - name: Infrastructure
      accounts:
        - name: acme-hops
          email: hops@acme.com
    - name: Workloads
      children:
        - name: Prod
          accounts:
            - name: acme-prod
              email: prod@acme.com
        - name: Non-Prod
    - name: Sandbox
  delegatedAdministrators:
    - servicePrincipal: ipam.amazonaws.com
      accountRef:
        name: acme-hops
  tags:
    organization: acme
    hops: "true"
