# Import an existing AWS Organization
# Use this when you already have an AWS Organization and want Crossplane to manage it
apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: Organization
metadata:
  name: my-org
  namespace: default
spec:
  # External name adopts the existing organization
  externalName: o-abc123xyz
  # Default managementPolicies applies to OUs, accounts, delegated admins (includes Delete)
  # managementPolicies: ["*"]  # default
  # Orphan only the Organization on deletion - don't delete the actual AWS org
  # OUs and other child resources will still be deleted
  organization:
    managementPolicies:
      - Create
      - Observe
      - Update
      - LateInitialize
  organizationalUnits:
    - path: Security
    - path: Infrastructure
  tags:
    organization: my-org
